output_dir: './results'
seed: 72580
width: 512
height: 512
num_inference_steps: 25
pad_frames: 15
n_sample_frames: 25
fps: 12.5
weight_dtype: 'fp16'
noise_aug_strength: 0.00
decode_chunk_size: 8
motion_bucket_id: 0
arcface_img_size: 512
input_expression_dim: 512
motion_expression_dim: 1018
num_img_tokens: 261
num_queries: 64
use_arcface: True
area: 1.05
frame_num: 10000
overlap: 3
shift_offset: 3
min_appearance_guidance_scale: 2.0
max_appearance_guidance_scale: 2.0
min_motion_guidance_scale: 2.0
max_motion_guidance_scale: 2.0
i2i_noise_strength: 1.0
ip_motion_scale: 1.0
num_adapter_embeds: [32]

pretrained_model_name_or_path: 'pretrained_weights'
det_path: 'pretrained_weights/yoloface_v5m.pt'
arcface_model_path: 'pretrained_weights/arcface.onnx'
unet_checkpoint_path: 'pretrained_weights/hyportrait/unet.pth'
pose_guider_checkpoint_path: 'pretrained_weights/hyportrait/pose_guider.pth'
dino_checkpoint_path: 'pretrained_weights/hyportrait/dino.pth'
image_proj_checkpoint_path: 'pretrained_weights/hyportrait/image_proj.pth'
motion_expression_checkpoint_path: 'pretrained_weights/hyportrait/expression.pth'
motion_pose_checkpoint_path: 'pretrained_weights/hyportrait/headpose.pth'
motion_proj_checkpoint_path: 'pretrained_weights/hyportrait/motion_proj.pth'